name: prod.yml
on:
  push:
    branches:
      - prod

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker image
        run: docker build -t dlanguet/devops-tp3:latest .
        
        
      - name: Push Docker image
        run: docker push dlanguet/devops-tp3:latest