name: prod.yml
on:
  push:
    branches:
      - prod

jobs:
  say-hello-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Echo Hello Prod
        run: echo "Hello Prod"
